AppBundle\Entity\Landingcarouselexpo:
    type: entity
    table: LandingCarouselExpo
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        type:
            type: boolean
            nullable: true
    lifecycleCallbacks: {  }
