AppBundle\Entity\Landing:
    type: entity
    table: landing
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        image:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        categorie:
            type: smallint
            nullable: false
            options:
                unsigned: true
    lifecycleCallbacks: {  }
