AppBundle\Entity\Landing:
    type: entity
    table: landing
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        carousselexpo:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: carousselExpo
        carousselartiste:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: carousselArtiste
    lifecycleCallbacks: {  }
