AppBundle\Entity\Users:
    type: entity
    table: users
    indexes:
        role:
            columns:
                - role
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        role:
            targetEntity: Roles
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                role:
                    referencedColumnName: role
            orphanRemoval: false
    lifecycleCallbacks: {  }
